name: Android UI tests

on:
  schedule:
    - cron: '0 0 * * *' # Every day at midnight UTC

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  instrumentation-tests:
    runs-on: [ self-hosted, Android ]

    env:
      ENV_PATH: "app/src/androidTest/java/com/infomaniak/mail/utils/Env.kt"
      UI_TEST_ACCOUNT_EMAIL: ${{ secrets.UI_TEST_ACCOUNT_EMAIL }}
      UI_TEST_ACCOUNT_PASSWORD: ${{ secrets.UI_TEST_ACCOUNT_PASSWORD }}

    steps:
      - name: Checkout the code
        uses: actions/checkout@v5.0.0
        with:
          token: ${{ github.token }}
          submodules: recursive

      - name: Create test env
        run: |
          mkdir -p "$(dirname "$ENV_PATH")"
          touch $ENV_PATH
          echo "package com.infomaniak.mail.utils; object Env { const val UI_TEST_ACCOUNT_EMAIL: String = \"$UI_TEST_ACCOUNT_EMAIL\"; const val UI_TEST_ACCOUNT_PASSWORD: String = \"$UI_TEST_ACCOUNT_PASSWORD\" }" > $ENV_PATH

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Clean gradle cache
        run: ./gradlew clean

      - name: Run UI tests
        run: |
          ./gradlew ui-testStandardDebugAndroidTest

      - name: Upload Test Report
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: ui-test-report
          path: app/build/reports/androidTests/managedDevice/debug/flavors/standard/allDevices

      - name: Notify KChat
        if: failure()
        env:
          KCHAT_TESTS_WEBHOOK_URL: ${{ secrets.KCHAT_TESTS_WEBHOOK_URL }}
        run: |
           RUN_URL="${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}"

           MESSAGE=":rotating_light: *Official Communication from CI JinPing*\n\nAn act of software disharmony has been detected.\n\nRepository: ${{ github.repository }}\nWorkflow run: $RUN_URL\n\nThe Central Committee requires immediate correction.\nThe failing tests have been documented.\nResistance is futile. Green pipeline is mandatory."

           curl -s -X POST "$KCHAT_TESTS_WEBHOOK_URL" \
             -H "Content-Type: application/json" \
           -d "{\"text\": \"$MESSAGE\"}"
